services:
  shukachi.seedagent.api:
    image: ${DOCKER_REGISTRY-}shukachiseedagentapi
    build:
      context: .
      dockerfile: Shukachi.SeedAgent.Api/Dockerfile
    env_file:
      - .env
  shukachi.seedagent.embeddingserver:
    image: ${DOCKER_REGISTRY-}shukachiseedagentembeddingserver
    build:
      context: .
      dockerfile: Shukachi.SeedAgent.EmbeddingServer/Dockerfile
    env_file:
      - .env
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
