services:
  shukachi.seedagent.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3000
      - LLM_MODEL_ID=${LLM_MODEL_ID}
      - LLM_MODEL_KEY=${LLM_MODEL_KEY}
      - QDRANT_VECTOR_SIZE=384
      - EMBEDDING_SERVER_URL=http://shukachi.seedagent.embeddingserver:3001
      - SEQ_SERVER_URL=http://seq:5341
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=shukachi.seedagent.api
    ports:
      - "3000:3000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  shukachi.seedagent.embeddingserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3001
    ports:
      - "3001:3001"
